stages:
   - build

build-sqlite-all:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [""]
  variables:
    RENEW_ACCOUNT_DB_TYPE: sqlite
    RENEW_DOCS_DB_TYPE: sqlite
    RENEW_SIM_DB_TYPE: sqlite
    RENEW_PROJ_DB_TYPE: sqlite

    IMAGE_TAG: $CI_REGISTRY_IMAGE:sqlite-all-latest
    DOCKER_FILE: Dockerfile

    KANIKO_REGISTRY_CREDS: >-
      {"auths":{
        "$CI_REGISTRY":{
          "username": "$CI_REGISTRY_USER",
          "password": "$CI_REGISTRY_PASSWORD"}}}
  script:
    - echo "$KANIKO_REGISTRY_CREDS" > /kaniko/.docker/config.json
    - /kaniko/executor
      --context "$CI_PROJECT_DIR"
      --build-arg "RENEW_ACCOUNT_DB_TYPE=$RENEW_ACCOUNT_DB_TYPE"
      --build-arg "RENEW_DOCS_DB_TYPE=$RENEW_DOCS_DB_TYPE"
      --build-arg "RENEW_SIM_DB_TYPE=$RENEW_SIM_DB_TYPE"
      --build-arg "RENEW_PROJ_DB_TYPE=$RENEW_PROJ_DB_TYPE"
      --dockerfile "$DOCKER_FILE"
      --destination "$IMAGE_TAG"
  tags:
    - tgi

build-mysql-all:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [""]
  variables:
    RENEW_ACCOUNT_DB_TYPE: mysql
    RENEW_DOCS_DB_TYPE: mysql
    RENEW_SIM_DB_TYPE: mysql
    RENEW_PROJ_DB_TYPE: mysql

    IMAGE_TAG: $CI_REGISTRY_IMAGE:mysql-all-latest
    DOCKER_FILE: Dockerfile

    KANIKO_REGISTRY_CREDS: >-
      {"auths":{
        "$CI_REGISTRY":{
          "username": "$CI_REGISTRY_USER",
          "password": "$CI_REGISTRY_PASSWORD"}}}
  script:
    - echo "$KANIKO_REGISTRY_CREDS" > /kaniko/.docker/config.json
    - /kaniko/executor
      --context "$CI_PROJECT_DIR"
      --build-arg "RENEW_ACCOUNT_DB_TYPE=$RENEW_ACCOUNT_DB_TYPE"
      --build-arg "RENEW_DOCS_DB_TYPE=$RENEW_DOCS_DB_TYPE"
      --build-arg "RENEW_SIM_DB_TYPE=$RENEW_SIM_DB_TYPE"
      --build-arg "RENEW_PROJ_DB_TYPE=$RENEW_PROJ_DB_TYPE"
      --dockerfile "$DOCKER_FILE"
      --destination "$IMAGE_TAG"
  tags:
    - tgi


build-postgresql-all:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [""]
  variables:
    RENEW_ACCOUNT_DB_TYPE: postgresql
    RENEW_DOCS_DB_TYPE: postgresql
    RENEW_SIM_DB_TYPE: postgresql
    RENEW_PROJ_DB_TYPE: postgresql

    IMAGE_TAG: $CI_REGISTRY_IMAGE:postgresql-all-latest
    DOCKER_FILE: Dockerfile

    KANIKO_REGISTRY_CREDS: >-
      {"auths":{
        "$CI_REGISTRY":{
          "username": "$CI_REGISTRY_USER",
          "password": "$CI_REGISTRY_PASSWORD"}}}
  script:
    - echo "$KANIKO_REGISTRY_CREDS" > /kaniko/.docker/config.json
    - /kaniko/executor
      --context "$CI_PROJECT_DIR"
      --build-arg "RENEW_ACCOUNT_DB_TYPE=$RENEW_ACCOUNT_DB_TYPE"
      --build-arg "RENEW_DOCS_DB_TYPE=$RENEW_DOCS_DB_TYPE"
      --build-arg "RENEW_SIM_DB_TYPE=$RENEW_SIM_DB_TYPE"
      --build-arg "RENEW_PROJ_DB_TYPE=$RENEW_PROJ_DB_TYPE"
      --dockerfile "$DOCKER_FILE"
      --destination "$IMAGE_TAG"
  tags:
    - tgi