12 
    de.renew.gui.CPNDrawing 9 
        CH.ifa.draw.figures.RectangleFigure "attributes" "attributes" 3 "FigureWithID" "Int" 742 "FrameColor" "Color" 224 224 224 255 "FillColor" "Color" 240 240 240 255 -12 -14 69 33  
        de.renew.netcomponents.NetComponentFigure "attributes" "attributes" 4 "LineStyle" "String" "1 2" "FigureWithID" "Int" 5029 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 4 REF 1 
            de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 4989 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 192 192 192 255 0 -6 24 16 NULL  
            de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 4988 75 -8 20 20 NULL  
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5021 2 24 2 76 2 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 3  
                CH.ifa.draw.figures.ChopEllipseConnector REF 4    REF 3 REF 4 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 5004 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 255 0 0 255 "FillColor" "Color" 255 199 158 255 91 -7 ">" "SansSerif" 1 12 0 REF 4 
            CH.ifa.draw.standard.OffsetLocator 9 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 5028 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 0 0 255 255 "FillColor" "Color" 255 199 158 255 19 -6 "<" "SansSerif" 1 12 0 REF 3 
            CH.ifa.draw.standard.OffsetLocator 10 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 4995 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 255 0 0 255 "FillColor" "Color" 255 199 158 255 -2 -7 ">" "SansSerif" 1 12 0 REF 3 
            CH.ifa.draw.standard.OffsetLocator -11 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  REF 5 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 5022 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 -1 -28 "OUT" "SansSerif" 1 12 0 REF 4 
            CH.ifa.draw.standard.OffsetLocator -73 -22 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  NULL  