12 
    de.renew.gui.CPNDrawing 25 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3526 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 53 -34 "COND" "SansSerif" 1 12 0 
            de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 3514 134 102 20 20 NULL  
            CH.ifa.draw.standard.OffsetLocator -73 -138 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3527 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 53 -34 "COND" "SansSerif" 1 12 0 
            de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 3516 145 -125 20 20 NULL  
            CH.ifa.draw.standard.OffsetLocator -84 89 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.contrib.TriangleFigure "attributes" "attributes" 3 "FrameColor" "Color" 224 224 224 255 "FigureWithID" "Int" 3503 "FillColor" "Color" 240 240 240 255 6 -131 135 264 6  
        de.renew.netcomponents.NetComponentFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3528 "FillColor" "Color" 255 199 158 255 "LineStyle" "String" "1 2" 12 
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 3507 "Visibility" "Boolean" "TRUE" 2 75 -5 104 -50 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.figures.ChopEllipseConnector 
                    de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 3506 "FillColor" "Color" 192 192 192 255 "Visibility" "Boolean" "TRUE" 59 -8 20 20 NULL   
                CH.ifa.draw.standard.ChopBoxConnector 
                    de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 3508 "FillColor" "Color" 192 192 192 255 "Visibility" "Boolean" "TRUE" 98 -66 24 16 NULL    
            de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 3504 "FillColor" "Color" 192 192 192 255 "Visibility" "Boolean" "TRUE" -7 -6 24 16 NULL  REF 2 
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 3509 "Visibility" "Boolean" "TRUE" 2 75 10 104 54 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.figures.ChopEllipseConnector REF 14  
                CH.ifa.draw.standard.ChopBoxConnector 
                    de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 3510 "FillColor" "Color" 192 192 192 255 "Visibility" "Boolean" "TRUE" 98 54 24 16 NULL    
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3515 2 116 -66 150 -107 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 16  
                CH.ifa.draw.figures.ChopEllipseConnector REF 6   REF 14 REF 6 REF 22 
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 3505 "Visibility" "Boolean" "TRUE" 2 17 2 60 2 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 17  
                CH.ifa.draw.figures.ChopEllipseConnector REF 14   
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3513 2 115 70 139 105 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 22  
                CH.ifa.draw.figures.ChopEllipseConnector REF 2   REF 16 REF 9  REF 17 REF 2 REF 14 REF 6 REF 22 REF 16 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 3511 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 "Visibility" "Boolean" "TRUE" "FrameColor" "Color" 255 199 158 255 96 22 "false" "SansSerif" 0 12 0 REF 18 
            CH.ifa.draw.standard.OffsetLocator 20 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 11 
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 3523 "TextColor" "Color" 0 0 255 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 "FrameColor" "Color" 255 199 158 255 20 -120 "[true]" "SansSerif" 0 18 0 REF 9 
            CH.ifa.draw.standard.OffsetLocator -30 -108 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    REF 18 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3520 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 65 -34 "IF" "SansSerif" 1 12 0 REF 14 
            CH.ifa.draw.standard.OffsetLocator 2 -28 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  REF 23 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 3522 "TextColor" "Color" 255 0 0 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 "FrameColor" "Color" 255 199 158 255 -8 -7 ">" "SansSerif" 1 12 0 REF 17 
            CH.ifa.draw.standard.OffsetLocator -10 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 3512 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 "Visibility" "Boolean" "TRUE" "FrameColor" "Color" 255 199 158 255 97 -34 "true" "SansSerif" 0 12 0 REF 11 
            CH.ifa.draw.standard.OffsetLocator 19 2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 3519 "TextColor" "Color" 255 0 0 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 "FrameColor" "Color" 255 199 158 255 161 -124 ">" "SansSerif" 1 12 0 REF 6 
            CH.ifa.draw.standard.OffsetLocator 9 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  REF 27 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 3521 "TextColor" "Color" 255 0 0 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 "FrameColor" "Color" 255 199 158 255 150 103 ">" "SansSerif" 1 12 0 REF 2 
            CH.ifa.draw.standard.OffsetLocator 9 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 3524 "TextColor" "Color" 0 0 255 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 "FrameColor" "Color" 255 199 158 255 14 84 "[false]" "SansSerif" 0 18 0 REF 9 
            CH.ifa.draw.standard.OffsetLocator -33 96 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 3517 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 "Visibility" "Boolean" "TRUE" "FrameColor" "Color" 255 199 158 255 26 -16 "cond" "SansSerif" 0 12 0 REF 27 
            CH.ifa.draw.standard.OffsetLocator 1 -10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 31 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 3518 "TextAlignment" "Int" 0 "FillColor" "Color" 255 199 158 255 "Visibility" "Boolean" "TRUE" "FrameColor" "Color" 255 199 158 255 -42 14 "$booleanCondition" "SansSerif" 0 12 0 REF 17 
            CH.ifa.draw.standard.OffsetLocator 5 20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  NULL  