12 
    de.renew.gui.CPNDrawing 28 
        CH.ifa.draw.contrib.TriangleFigure "attributes" "attributes" 3 "FigureWithID" "Int" 63131 "FrameColor" "Color" 224 224 224 255 "FillColor" "Color" 240 240 240 255 -6 -74 198 152 2  
        de.renew.netcomponents.NetComponentFigure "attributes" "attributes" 3 "FigureWithID" "Int" 63166 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 14 
            de.renew.gui.PlaceFigure "attributes" "attributes" 2 "FigureWithID" "Int" 63133 "FillColor" "Color" 192 192 192 255 -58 -68 20 20 NULL  
            de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 63132 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 -9 -5 24 16 NULL  
            de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 63135 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 192 192 192 255 34 -40 54 25 NULL  
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 63146 2 79 -19 109 -4 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.figures.ChopEllipseConnector REF 5  
                CH.ifa.draw.standard.ChopBoxConnector 
                    de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 63152 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 109 -5 24 16 NULL    
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 63155 2 133 2 175 2 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 9  
                CH.ifa.draw.figures.ChopEllipseConnector 
                    de.renew.gui.PlaceFigure "attributes" "attributes" 2 "FigureWithID" "Int" 63136 "FillColor" "Color" 255 255 255 255 174 -8 20 20 NULL    REF 9 
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 63154 2 72 2 109 2 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.figures.ChopEllipseConnector 
                    de.renew.gui.PlaceFigure "attributes" "attributes" 2 "FigureWithID" "Int" 63150 "FillColor" "Color" 255 255 255 255 52 -8 20 20 NULL   
                CH.ifa.draw.standard.ChopBoxConnector REF 9   
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 63158 2 127 -5 164 -46 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 9  
                CH.ifa.draw.figures.ChopEllipseConnector 
                    de.renew.gui.PlaceFigure "attributes" "attributes" 2 "FigureWithID" "Int" 63159 "FillColor" "Color" 192 192 192 255 159 -64 20 20 NULL    
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 63147 2 -4 -5 -42 -50 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  NULL "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 4  
                CH.ifa.draw.figures.ChopEllipseConnector REF 3   REF 24 REF 18 REF 14 REF 1 
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 63151 2 15 2 53 2 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 4  
                CH.ifa.draw.figures.ChopEllipseConnector REF 18    
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 63153 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 -74 18 ":access(kb);\nkb:newPlan(AgentletHelper\n.P_SEND_REQUEST)" "SansSerif" 0 12 0 REF 4 
            CH.ifa.draw.standard.OffsetLocator -1 40 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 63142 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 92 -22 "s" "SansSerif" 0 12 0 REF 6 
            CH.ifa.draw.standard.OffsetLocator 1 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 63160 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 143 -41 "id" "SansSerif" 0 12 0 REF 20 
            CH.ifa.draw.standard.OffsetLocator 3 -7 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 63144 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 255 0 0 255 "FillColor" "Color" 255 199 158 255 193 -7 ">" "SansSerif" 1 12 0 REF 14 
            CH.ifa.draw.standard.OffsetLocator 12 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 63148 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 0 0 255 255 "FillColor" "Color" 255 199 158 255 -20 80 "[send web event request]" "SansSerif" 0 18 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator -6 91 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 63141 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 66 15 ":newExchange(s,o,id);" "SansSerif" 0 12 0 REF 9 
            CH.ifa.draw.standard.OffsetLocator 5 20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 63143 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 -34 -48 "o" "SansSerif" 0 12 0 REF 25 
            CH.ifa.draw.standard.OffsetLocator -8 -12 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 63156 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 31 -6 "o" "SansSerif" 0 12 0 REF 29 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 63157 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 87 -6 "o" "SansSerif" 0 12 0 REF 15 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 63167 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 0 0 255 255 "FillColor" "Color" 255 199 158 255 -31 -133 "[@param o WebEvent or VTSequence \nof WebEvents\n@result id Request ID]" "SansSerif" 0 12 0 REF 5 
            CH.ifa.draw.standard.OffsetLocator 13 -80 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   4  REF 18 REF 3 REF 4 REF 5 REF 9 REF 24 REF 14 REF 6 REF 10 REF 15 REF 20 REF 25 REF 29 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 63145 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 -21 -49 "AgentletHelper.\nDC_ACTION_WEB_EVENT_REQUEST" "SansSerif" 0 11 0 REF 5 
            CH.ifa.draw.standard.OffsetLocator 8 -5 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 63101 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 255 0 0 255 "FillColor" "Color" 255 199 158 255 -11 -5 ">" "SansSerif" 1 12 0 REF 4 
            CH.ifa.draw.standard.OffsetLocator -11 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 63168 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 -10 -83 "DC-WEB-SEND-REQUEST" "SansSerif" 1 12 0 REF 14 
            CH.ifa.draw.standard.OffsetLocator -122 -77 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  NULL  