12 
    de.renew.gui.CPNDrawing 18 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 63098 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 -44 -6 "DC-WEB-SEND-ANSWER" "SansSerif" 1 12 0 
            de.renew.gui.PlaceFigure "attributes" "attributes" 2 "FigureWithID" "Int" 63086 "FillColor" "Color" 255 255 255 255 119 -8 20 20 NULL  
            CH.ifa.draw.standard.OffsetLocator -103 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.contrib.TriangleFigure "attributes" "attributes" 3 "FrameColor" "Color" 224 224 224 255 "FigureWithID" "Int" 63082 "FillColor" "Color" 240 240 240 255 -89 -74 198 152 6  
        de.renew.netcomponents.NetComponentFigure "attributes" "attributes" 3 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 63083 "FillColor" "Color" 255 199 158 255 8 
            de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 63084 "FillColor" "Color" 192 192 192 255 -4 -28 54 25 NULL  
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 63091 2 -120 -51 -88 -6 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.figures.ChopEllipseConnector 
                    de.renew.gui.PlaceFigure "attributes" "attributes" 2 "FigureWithID" "Int" 63087 "FillColor" "Color" 192 192 192 255 -136 -69 20 20 NULL   
                CH.ifa.draw.standard.ChopBoxConnector 
                    de.renew.gui.TransitionFigure "attributes" "attributes" 2 "FigureWithID" "Int" 63085 "FillColor" "Color" 255 255 255 255 -94 -6 24 16 NULL    REF 13 
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 63093 2 -70 2 120 2 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 13  
                CH.ifa.draw.figures.ChopEllipseConnector REF 2   REF 2 REF 11 
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 63095 2 -1 -12 -70 -1 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.figures.ChopEllipseConnector REF 7  
                CH.ifa.draw.standard.ChopBoxConnector REF 13   REF 5  REF 7 REF 13 REF 2 REF 11 
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 63065 "TextColor" "Color" 0 0 255 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 "FrameColor" "Color" 255 199 158 255 -123 -122 "[@param name Name of WebEventAction\n@result seq VTSequence of WebEvents]" "SansSerif" 0 12 0 REF 5 
            CH.ifa.draw.standard.OffsetLocator -17 -107 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 63088 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 -39 -15 "s" "SansSerif" 0 12 0 REF 18 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 63089 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 -30 9 ":exchange(s,o,id);" "SansSerif" 0 12 0 REF 13 
            CH.ifa.draw.standard.OffsetLocator 100 15 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 63090 "TextColor" "Color" 0 0 255 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 "FrameColor" "Color" 255 199 158 255 -110 80 "[send web event response]" "SansSerif" 0 18 0 REF 5 
            CH.ifa.draw.standard.OffsetLocator -6 91 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    REF 8 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 63092 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 -119 -39 "[id,o]" "SansSerif" 0 12 0 REF 8 
            CH.ifa.draw.standard.OffsetLocator -1 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 14 
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 63094 "TextColor" "Color" 255 0 0 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 "FrameColor" "Color" 255 199 158 255 138 -7 ">" "SansSerif" 1 12 0 REF 2 
            CH.ifa.draw.standard.OffsetLocator 12 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    REF 18 
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 63096 "TextColor" "Color" 255 0 0 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 "FrameColor" "Color" 255 199 158 255 -96 -6 ">" "SansSerif" 1 12 0 REF 13 
            CH.ifa.draw.standard.OffsetLocator -11 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 63097 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 -52 -40 "AgentletHelper.\nDC_ACTION_HANDLE_WEB_EVENTS" "SansSerif" 0 11 0 REF 7 
            CH.ifa.draw.standard.OffsetLocator 15 -8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  NULL  