12 
    de.renew.gui.CPNDrawing 18 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 63011 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 -22 -6 "DC-WEB-SEND-INFORM" "SansSerif" 1 12 0 
            de.renew.gui.PlaceFigure "attributes" "attributes" 2 "FigureWithID" "Int" 62991 "FillColor" "Color" 255 255 255 255 132 -8 20 20 NULL  
            CH.ifa.draw.standard.OffsetLocator -94 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.contrib.TriangleFigure "attributes" "attributes" 3 "FigureWithID" "Int" 62985 "FrameColor" "Color" 224 224 224 255 "FillColor" "Color" 240 240 240 255 -49 -74 198 152 2  
        de.renew.netcomponents.NetComponentFigure "attributes" "attributes" 3 "FigureWithID" "Int" 63010 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 8 
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 62995 2 -36 2 133 2 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector 
                    de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 62989 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 -60 -6 24 16 NULL   
                CH.ifa.draw.figures.ChopEllipseConnector REF 2   
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 63008 2 -71 -46 -52 -6 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.figures.ChopEllipseConnector 
                    de.renew.gui.PlaceFigure "attributes" "attributes" 2 "FigureWithID" "Int" 63007 "FillColor" "Color" 192 192 192 255 -85 -65 20 20 NULL   
                CH.ifa.draw.standard.ChopBoxConnector REF 10   REF 15 
            de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 63002 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 192 192 192 255 3 -31 54 25 NULL  REF 5 REF 2 
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 63004 2 8 -13 -36 -2 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.figures.ChopEllipseConnector REF 17  
                CH.ifa.draw.standard.ChopBoxConnector REF 10   REF 10  REF 12 REF 17 REF 2 REF 10 REF 7 
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 62982 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 0 0 255 255 "FillColor" "Color" 255 199 158 255 -61 80 "[send web event inform]" "SansSerif" 0 18 0 REF 5 
            CH.ifa.draw.standard.OffsetLocator -8 91 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 62999 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 -29 9 ":access(kb);\nkb:newPlan(s,o);" "SansSerif" 0 12 0 REF 10 
            CH.ifa.draw.standard.OffsetLocator 64 24 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 62998 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 255 0 0 255 "FillColor" "Color" 255 199 158 255 -62 -6 ">" "SansSerif" 1 12 0 REF 10 
            CH.ifa.draw.standard.OffsetLocator -11 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 63006 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 0 0 255 255 "FillColor" "Color" 255 199 158 255 -71 -114 "[@param o WebEvent or VTSequence\nof WebEvents]" "SansSerif" 0 12 0 REF 5 
            CH.ifa.draw.standard.OffsetLocator -17 -99 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    REF 18 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 63003 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 -16 -40 "AgentletHelper\n.P_SEND_INFORM" "SansSerif" 0 11 0 REF 17 
            CH.ifa.draw.standard.OffsetLocator 0 -5 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 63009 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 -67 -38 "o" "SansSerif" 0 12 0 REF 12 
            CH.ifa.draw.standard.OffsetLocator -2 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 63005 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 -17 -16 "s" "SansSerif" 0 12 0 REF 18 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 15 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 63012 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 255 0 0 255 "FillColor" "Color" 255 199 158 255 147 -6 ">" "SansSerif" 1 12 0 REF 2 
            CH.ifa.draw.standard.OffsetLocator 8 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  NULL  