12 
    de.renew.gui.CPNDrawing 23 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 63083 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 -52 -6 "DC-WEB-RECEIVE-REQUEST" "SansSerif" 1 12 0 
            de.renew.gui.PlaceFigure "attributes" "attributes" 2 "FigureWithID" "Int" 63053 "FillColor" "Color" 255 255 255 255 109 -8 20 20 NULL  
            CH.ifa.draw.standard.OffsetLocator -91 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.contrib.TriangleFigure "attributes" "attributes" 3 "FigureWithID" "Int" 63045 "FrameColor" "Color" 224 224 224 255 "FillColor" "Color" 240 240 240 255 -71 -74 198 152 2  
        de.renew.netcomponents.NetComponentFigure "attributes" "attributes" 3 "FigureWithID" "Int" 63079 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 10 REF 5 
            de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 63047 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 -74 -5 24 16 NULL  
            de.renew.gui.PlaceFigure "attributes" "attributes" 2 "FigureWithID" "Int" 63050 "FillColor" "Color" 192 192 192 255 15 -90 20 20 NULL  
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 63076 2 -63 -50 -63 -5 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.figures.ChopEllipseConnector 
                    de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 63048 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 192 192 192 255 -90 -74 54 25 NULL   
                CH.ifa.draw.standard.ChopBoxConnector REF 7   
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 63074 2 -8 -14 -50 -1 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.figures.ChopEllipseConnector 
                    de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 63052 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 192 192 192 255 -14 -33 54 25 NULL   
                CH.ifa.draw.standard.ChopBoxConnector REF 7   REF 11 REF 15 REF 2 
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 63067 2 -54 -5 19 -73 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 7  
                CH.ifa.draw.figures.ChopEllipseConnector REF 8   
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 63078 2 -50 2 110 2 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 7  
                CH.ifa.draw.figures.ChopEllipseConnector REF 2    REF 7 REF 8 REF 11 REF 15 REF 2 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 63064 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 -80 -45 "name" "SansSerif" 0 12 0 REF 9 
            CH.ifa.draw.standard.OffsetLocator -1 -9 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 63063 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 -67 -70 "\"\"" "SansSerif" 0 12 0 REF 11 
            CH.ifa.draw.standard.OffsetLocator 1 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 9 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 63055 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 -74 14 "guard wea.getName().equals(name);\n:newExchange(s,wea,id);\naction seq = wea.getAllEvents();" "SansSerif" 0 12 0 REF 7 
            CH.ifa.draw.standard.OffsetLocator 90 36 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 63059 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 -31 -18 "s" "SansSerif" 0 12 0 REF 13 
            CH.ifa.draw.standard.OffsetLocator 1 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 63077 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 -22 -60 "[id,seq]" "SansSerif" 0 12 0 REF 17 
            CH.ifa.draw.standard.OffsetLocator 16 -13 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 63072 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 255 0 0 255 "FillColor" "Color" 255 199 158 255 128 -7 ">" "SansSerif" 1 12 0 REF 2 
            CH.ifa.draw.standard.OffsetLocator 12 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 63066 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 -69 -43 "AgentletHelper.\nDC_ACTION_HANDLE_WEB_EVENTS" "SansSerif" 0 11 0 REF 15 
            CH.ifa.draw.standard.OffsetLocator 8 -6 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 13 REF 17 
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 63056 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 0 0 255 255 "FillColor" "Color" 255 199 158 255 -95 80 "[receive web event request]" "SansSerif" 0 18 0 REF 5 
            CH.ifa.draw.standard.OffsetLocator -6 91 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    REF 21 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 63080 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 0 0 255 255 "FillColor" "Color" 255 199 158 255 -104 -123 "[@param name Name of WebEventAction\n@result seq VTSequence of WebEvents]" "SansSerif" 0 12 0 REF 15 
            CH.ifa.draw.standard.OffsetLocator -1 -85 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   4  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 63081 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 39 -70 "dc-call" "SansSerif" 1 12 0 REF 15 
            CH.ifa.draw.standard.OffsetLocator 45 -41 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 63082 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 255 0 0 255 "FillColor" "Color" 255 199 158 255 -75 -5 ">" "SansSerif" 0 12 0 REF 7 
            CH.ifa.draw.standard.OffsetLocator -10 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    NULL  