12 
    de.renew.gui.CPNDrawing 23 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 63109 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 -83 -5 "DC-WEB-RECEIVE-INFORM" "SansSerif" 1 12 0 
            de.renew.gui.PlaceFigure "attributes" "attributes" 2 "FigureWithID" "Int" 63089 "FillColor" "Color" 255 255 255 255 82 -8 20 20 NULL  
            CH.ifa.draw.standard.OffsetLocator -97 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.contrib.TriangleFigure "attributes" "attributes" 3 "FrameColor" "Color" 224 224 224 255 "FigureWithID" "Int" 63085 "FillColor" "Color" 240 240 240 255 -98 -74 198 152 2  
        de.renew.netcomponents.NetComponentFigure "attributes" "attributes" 3 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 63105 "FillColor" "Color" 255 199 158 255 10 
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 63090 2 -77 2 83 2 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector 
                    de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 63087 "FillColor" "Color" 255 255 255 255 -101 -5 24 16 NULL   
                CH.ifa.draw.figures.ChopEllipseConnector REF 2   REF 10 
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 63096 2 -36 -12 -77 -1 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.figures.ChopEllipseConnector 
                    de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 63088 "FillColor" "Color" 192 192 192 255 -41 -31 54 25 NULL   
                CH.ifa.draw.standard.ChopBoxConnector REF 10   
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 63091 2 -90 -50 -90 -5 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.figures.ChopEllipseConnector 
                    de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 63086 "FillColor" "Color" 192 192 192 255 -117 -74 54 25 NULL   
                CH.ifa.draw.standard.ChopBoxConnector REF 10   REF 5 REF 18 REF 14 
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 63102 2 -81 -5 -16 -69 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 10  
                CH.ifa.draw.figures.ChopEllipseConnector 
                    de.renew.gui.PlaceFigure "attributes" "attributes" 2 "FigureWithID" "Int" 63103 "FillColor" "Color" 192 192 192 255 -20 -86 20 20 NULL    REF 24 REF 2  REF 10 REF 18 REF 14 REF 24 REF 2 REF 7 REF 12 REF 16 REF 20 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 63098 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 -120 12 "guard wea.getName().equals(name);\n:exchange(s,wea);\naction seq = wea.getAllEvents();" "SansSerif" 0 12 0 REF 10 
            CH.ifa.draw.standard.OffsetLocator 71 34 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 63104 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 -43 -60 "seq" "SansSerif" 0 12 0 REF 20 
            CH.ifa.draw.standard.OffsetLocator 16 -15 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 63097 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 -59 -16 "s" "SansSerif" 0 12 0 REF 12 
            CH.ifa.draw.standard.OffsetLocator 1 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 63095 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 -94 -70 "\"\"" "SansSerif" 0 12 0 REF 18 
            CH.ifa.draw.standard.OffsetLocator 1 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 63094 "TextColor" "Color" 255 0 0 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 "FrameColor" "Color" 255 199 158 255 101 -7 ">" "SansSerif" 1 12 0 REF 2 
            CH.ifa.draw.standard.OffsetLocator 12 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 63099 "TextColor" "Color" 0 0 255 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 "FrameColor" "Color" 255 199 158 255 -118 80 "[receive web event inform]" "SansSerif" 0 18 0 REF 5 
            CH.ifa.draw.standard.OffsetLocator -6 91 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 63100 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 -107 -45 "name" "SansSerif" 0 12 0 REF 16 
            CH.ifa.draw.standard.OffsetLocator -1 -9 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 63106 "TextColor" "Color" 0 0 255 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 "FrameColor" "Color" 255 199 158 255 -135 -152 "[@param name Name of WebEventAction\n@result seq VTSequence of WebEvents]" "SansSerif" 0 12 0 REF 14 
            CH.ifa.draw.standard.OffsetLocator -5 -116 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   4  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 63107 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 -61 -113 "dc-simple-call" "SansSerif" 1 12 0 REF 14 
            CH.ifa.draw.standard.OffsetLocator -5 -86 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 62994 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 -76 -42 "AgentletHelper.\nDC_ACTION_HANDLE_WEB_EVENTS" "SansSerif" 0 11 0 REF 14 
            CH.ifa.draw.standard.OffsetLocator 28 -7 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 63108 "TextColor" "Color" 255 0 0 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 "FrameColor" "Color" 255 199 158 255 -103 -5 ">" "SansSerif" 0 12 0 REF 10 
            CH.ifa.draw.standard.OffsetLocator -11 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    NULL  