12 
    de.renew.gui.CPNDrawing 42 
        CH.ifa.draw.figures.RoundRectangleFigure "attributes" "attributes" 3 "FigureWithID" "Int" 525 "FrameColor" "Color" 224 224 224 255 "FillColor" "Color" 240 240 240 255 -28 -111 152 150 114 114  
        de.renew.netcomponents.NetComponentFigure "attributes" "attributes" 3 "FigureWithID" "Int" 526 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 23 REF 1 
            de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 289 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 224 224 255 255 -41 -110 20 20 NULL 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 288 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 224 224 255 255 -44 -270 20 20 NULL   
            de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 281 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 192 192 192 255 78 -82 24 16 NULL  
            de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 276 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 192 192 192 255 36 -85 20 20 NULL  
            de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 267 "FrameColor" "Color" 0 0 0 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 192 192 192 255 -7 -49 20 20 NULL  
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 280 "FillColor" "Color" 254 254 254 255 2 56 -75 78 -75 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.figures.ChopEllipseConnector REF 6  
                CH.ifa.draw.standard.ChopBoxConnector REF 5   
            de.renew.gui.DoubleArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 273 2 3 -6 3 -29 NULL 
                de.renew.gui.DoubleArrowTip 0.4 8.0 8.0 1  "de.renew.gui.DoubleArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector 
                    de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 265 "FrameColor" "Color" 0 0 0 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 192 192 192 255 -9 -6 24 16 NULL   
                CH.ifa.draw.figures.ChopEllipseConnector REF 7   
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 275 2 16 -75 37 -75 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector 
                    de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 269 "FrameColor" "Color" 0 0 0 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 192 192 192 255 -8 -83 24 16 NULL   
                CH.ifa.draw.figures.ChopEllipseConnector REF 6   
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 277 2 4 -83 4 -117 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 20  
                CH.ifa.draw.figures.ChopEllipseConnector 
                    de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 278 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 -6 -137 20 20 NULL    
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 274 2 15 2 39 2 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 15  
                CH.ifa.draw.figures.ChopEllipseConnector 
                    de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 268 "FrameColor" "Color" 0 0 0 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 192 192 192 255 38 -8 20 20 NULL    REF 15 
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 287 2 -8 -83 -23 -94 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 20  
                CH.ifa.draw.figures.ChopEllipseConnector REF 3   REF 31 
            de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 266 "FrameColor" "Color" 0 0 0 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 192 192 192 255 78 -6 24 16 NULL  
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 282 "FillColor" "Color" 254 254 254 255 2 89 -66 89 -45 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 5  
                CH.ifa.draw.figures.ChopEllipseConnector 
                    de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 283 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 192 192 192 255 79 -46 20 20 NULL    
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 270 "Visibility" "Boolean" "TRUE" 2 3 -48 3 -67 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.figures.ChopEllipseConnector REF 7  
                CH.ifa.draw.standard.ChopBoxConnector REF 20   
            de.renew.gui.DoubleArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 279 2 89 -26 89 -6 NULL 
                de.renew.gui.DoubleArrowTip 0.4 8.0 8.0 1  "de.renew.gui.DoubleArrowTip" 
                CH.ifa.draw.figures.ChopEllipseConnector REF 41  
                CH.ifa.draw.standard.ChopBoxConnector REF 36   
            de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 272 "FrameColor" "Color" 0 0 0 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 112 219 147 255 131 -8 20 20 NULL  REF 26 REF 41 
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 286 2 58 2 78 2 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.figures.ChopEllipseConnector REF 31  
                CH.ifa.draw.standard.ChopBoxConnector REF 36   REF 20 
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 271 "Visibility" "Boolean" "TRUE" 2 102 2 132 2 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 36  
                CH.ifa.draw.figures.ChopEllipseConnector REF 50    REF 3 REF 5 REF 6 REF 7 REF 15 REF 31 REF 36 REF 50 REF 26 REF 41 REF 20 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 297 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 7 -67 "o" "SansSerif" 0 12 0 REF 42 
            CH.ifa.draw.standard.OffsetLocator 7 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 296 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 80 -66 "o" "SansSerif" 0 12 0 REF 37 
            CH.ifa.draw.standard.OffsetLocator -6 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 298 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 94 -28 "os" "SansSerif" 0 12 0 REF 46 
            CH.ifa.draw.standard.OffsetLocator 11 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 292 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 20 -16 "os" "SansSerif" 0 12 0 REF 27 
            CH.ifa.draw.standard.OffsetLocator -1 -10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 8 REF 12 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 299 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 9 -28 "os" "SansSerif" 0 12 0 REF 12 
            CH.ifa.draw.standard.OffsetLocator 12 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 17 REF 22 REF 27 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 294 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 21 -75 "o" "SansSerif" 0 12 0 REF 17 
            CH.ifa.draw.standard.OffsetLocator -2 8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 6 "TextAlignment" "Int" 1 "FigureWithID" "Int" 521 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 255 0 0 255 "TextType" "Int" 0 "FillColor" "Color" 255 199 158 255 -11 -6 ">" "SansSerif" 1 12 0 REF 15 
            CH.ifa.draw.standard.OffsetLocator -11 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 6 "TextAlignment" "Int" 1 "FigureWithID" "Int" 523 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 255 0 0 255 "TextType" "Int" 0 "FillColor" "Color" 255 199 158 255 0 -147 "^" "SansSerif" 1 14 0 REF 26 
            CH.ifa.draw.standard.OffsetLocator 0 -10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 291 "FrameColor" "Color" 255 199 158 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 254 254 254 255 -14 -108 "o" "SansSerif" 0 12 0 REF 32 
            CH.ifa.draw.standard.OffsetLocator 5 -11 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 32 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 295 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 62 -75 "o" "SansSerif" 0 12 0 REF 8 
            CH.ifa.draw.standard.OffsetLocator -2 8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 37 REF 42 
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 6 "TextAlignment" "Int" 1 "FigureWithID" "Int" 522 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 255 0 0 255 "TextType" "Int" 0 "FillColor" "Color" 255 199 158 255 146 -8 ">" "SansSerif" 1 12 0 REF 50 
            CH.ifa.draw.standard.OffsetLocator 8 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    REF 46 
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 6 "TextAlignment" "Int" 1 "FigureWithID" "Int" 524 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 255 0 0 255 "TextType" "Int" 0 "FillColor" "Color" 255 199 158 255 87 -90 "v" "SansSerif" 1 12 0 REF 5 
            CH.ifa.draw.standard.OffsetLocator 0 -8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 300 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 61 -16 "os" "SansSerif" 0 12 0 REF 51 
            CH.ifa.draw.standard.OffsetLocator -1 -10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 51 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 290 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 -53 -129 "Object" "SansSerif" 1 12 0 REF 3 
            CH.ifa.draw.standard.OffsetLocator -2 -21 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  REF 55 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 0 "FigureWithID" "Int" 293 "FrameColor" "Color" 255 199 158 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 255 199 158 255 -29 17 "action os = v.toArray();" "SansSerif" 0 12 0 REF 15 
            CH.ifa.draw.standard.OffsetLocator 30 23 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 4 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 306 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 -90 -273 "Object" "SansSerif" 1 12 0 REF 4 
            CH.ifa.draw.standard.OffsetLocator -36 -5 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 305 "FrameColor" "Color" 255 199 158 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 255 199 158 255 31 -44 "FORALL" "SansSerif" 1 12 0 REF 50
            CH.ifa.draw.standard.OffsetLocator -93 -38 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  NULL  