12 
    de.renew.gui.CPNDrawing 39 
        CH.ifa.draw.contrib.TriangleFigure "attributes" "attributes" 3 "FigureWithID" "Int" 3606 "FrameColor" "Color" 224 224 224 255 "FillColor" "Color" 240 240 240 255 -51 -191 163 220 3  
        de.renew.netcomponents.NetComponentFigure "attributes" "attributes" 3 "FigureWithID" "Int" 3842 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 17 
            de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 3621 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 192 192 192 255 75 -124 24 16 NULL  
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 3624 "Visibility" "Boolean" "TRUE" 2 47 -60 81 -108 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.figures.ChopEllipseConnector 
                    de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 3623 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 192 192 192 255 31 -63 20 20 NULL   
                CH.ifa.draw.standard.ChopBoxConnector REF 3   
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 3619 "Visibility" "Boolean" "TRUE" 2 54 2 75 2 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.figures.ChopEllipseConnector 
                    de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 3618 "FrameColor" "Color" 0 0 0 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 192 192 192 255 34 -8 20 20 NULL   
                CH.ifa.draw.standard.ChopBoxConnector 
                    de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 3620 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 192 192 192 255 75 -6 24 16 NULL    
            de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 3616 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 192 192 192 255 -10 -6 24 16 NULL  
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3632 2 94 -6 118 -29 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 14  
                CH.ifa.draw.figures.ChopEllipseConnector 
                    de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 3634 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 224 224 255 255 114 -46 20 20 NULL 
                        de.renew.gui.PlaceFigure "attributes" "attributes" 2 "FigureWithID" "Int" 3633 "FillColor" "Color" 224 224 255 255 -23 -287 20 20 NULL     
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3630 2 99 2 131 2 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 14  
                CH.ifa.draw.figures.ChopEllipseConnector 
                    de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 3631 130 -8 20 20 NULL    REF 1 REF 14 REF 12 REF 7 
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 3622 "Visibility" "Boolean" "TRUE" 2 7 -6 36 -45 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 15  
                CH.ifa.draw.figures.ChopEllipseConnector REF 7   
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 3627 "Visibility" "Boolean" "TRUE" 2 87 -43 87 -6 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.figures.ChopEllipseConnector 
                    de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 3626 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 192 192 192 255 77 -63 20 20 NULL   
                CH.ifa.draw.standard.ChopBoxConnector REF 14   
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 3617 "Visibility" "Boolean" "TRUE" 2 14 2 35 2 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 15  
                CH.ifa.draw.figures.ChopEllipseConnector REF 12   
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 3625 "Visibility" "Boolean" "TRUE" 2 87 -108 87 -62 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 3  
                CH.ifa.draw.figures.ChopEllipseConnector REF 34   REF 34 REF 20 REF 26  REF 3 REF 15 REF 14 REF 12 REF 7 REF 34 REF 20 REF 26 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 3639 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 255 0 0 255 "FillColor" "Color" 255 199 158 255 -12 -7 ">" "SansSerif" 1 12 0 REF 15 
            CH.ifa.draw.standard.OffsetLocator -11 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 3638 "FrameColor" "Color" 255 199 158 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 255 199 158 255 75 -145 ":in(p)" "SansSerif" 0 12 0 REF 3 
            CH.ifa.draw.standard.OffsetLocator 2 -21 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 4 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 3636 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 100 -33 "p" "SansSerif" 0 12 0 REF 16 
            CH.ifa.draw.standard.OffsetLocator -3 -7 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 9 REF 16 REF 22 
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 3840 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 0 0 255 255 "FillColor" "Color" 255 199 158 255 -29 42 "[comment]" "SansSerif" 0 18 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator -12 136 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 3628 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 89 -93 "p" "SansSerif" 0 12 0 REF 40 
            CH.ifa.draw.standard.OffsetLocator 5 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 3640 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 255 0 0 255 "FillColor" "Color" 255 199 158 255 147 -7 ">" "SansSerif" 1 12 0 REF 26 
            CH.ifa.draw.standard.OffsetLocator 10 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 3641 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 117 -44 "P2" "SansSerif" 1 12 0 REF 20 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  REF 27 REF 31 REF 36 REF 40 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 3629 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 90 -33 "p" "SansSerif" 0 12 0 REF 31 
            CH.ifa.draw.standard.OffsetLocator 6 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 3841 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 0 0 255 255 "FillColor" "Color" 255 199 158 255 51 -238 "[fromAgent]" "SansSerif" 0 18 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 73 -144 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3607 2 -3 -277 26 -277 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 21  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 3608 26 -285 24 16 NULL    REF 75 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 3609 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 8 -285 "p" "SansSerif" 0 12 0 REF 71 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3610 2 50 -277 93 -277 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 75  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 2 "FigureWithID" "Int" 3611 "FillColor" "Color" 224 224 255 255 92 -287 20 20 NULL    REF 83 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 3612 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 68 -285 "p" "SansSerif" 0 12 0 REF 79 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 2 "FigureWithID" "Int" 3613 "FillColor" "Color" 224 224 255 255 92 -263 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3614 3 38 -269 38 -253 93 -253 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 75  
            CH.ifa.draw.figures.ChopEllipseConnector REF 87   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 3615 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 115 -284 "Perf2" "SansSerif" 1 12 0 REF 83 
            CH.ifa.draw.standard.OffsetLocator 29 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  REF 21 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 3635 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 -19 -285 "P2" "SansSerif" 1 12 0 REF 21 
            CH.ifa.draw.standard.OffsetLocator 1 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 3637 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 57 -54 "IN" "SansSerif" 1 12 0 REF 26 
            CH.ifa.draw.standard.OffsetLocator -76 -48 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  NULL  