12 
    de.renew.gui.CPNDrawing 25 
        CH.ifa.draw.contrib.TriangleFigure "attributes" "attributes" 3 "FrameColor" "Color" 224 224 224 255 "FigureWithID" "Int" 4985 "FillColor" "Color" 240 240 240 255 -22 -193 163 220 5  
        de.renew.netcomponents.NetComponentFigure "attributes" "attributes" 3 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 5009 "FillColor" "Color" 255 199 158 255 15 
            de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 4989 "FillColor" "Color" 192 192 192 255 "Visibility" "Boolean" "TRUE" -8 -6 24 16 NULL  
            de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 4987 "FillColor" "Color" 192 192 192 255 "Visibility" "Boolean" "TRUE" 35 -69 20 20 NULL  
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 5001 "Visibility" "Boolean" "TRUE" 2 3 -6 3 -43 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 3  
                CH.ifa.draw.figures.ChopEllipseConnector 
                    de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 4990 "FillColor" "Color" 192 192 192 255 "Visibility" "Boolean" "TRUE" -7 -63 20 20 NULL    
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 4997 "Visibility" "Boolean" "TRUE" 2 3 -62 3 -109 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.figures.ChopEllipseConnector REF 9  
                CH.ifa.draw.standard.ChopBoxConnector 
                    de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 4992 "FillColor" "Color" 192 192 192 255 "Visibility" "Boolean" "TRUE" -8 -125 24 16 NULL    
            de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 4988 132 -8 20 20 NULL  
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 5005 "Visibility" "Boolean" "TRUE" 2 16 2 36 2 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 3  
                CH.ifa.draw.figures.ChopEllipseConnector 
                    de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 4991 "FillColor" "Color" 192 192 192 255 "Visibility" "Boolean" "TRUE" 35 -8 20 20 NULL    
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5002 2 101 2 133 2 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector 
                    de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 4986 "FillColor" "Color" 192 192 192 255 "Visibility" "Boolean" "TRUE" 77 -6 24 16 NULL   
                CH.ifa.draw.figures.ChopEllipseConnector REF 15   REF 1 REF 14 
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 5000 "Visibility" "Boolean" "TRUE" 2 9 -109 40 -66 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 14  
                CH.ifa.draw.figures.ChopEllipseConnector REF 4   
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 5003 "Visibility" "Boolean" "TRUE" 2 51 -51 83 -6 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.figures.ChopEllipseConnector REF 4  
                CH.ifa.draw.standard.ChopBoxConnector REF 24   REF 24 REF 20 REF 9 
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 4999 "Visibility" "Boolean" "TRUE" 2 55 2 77 2 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.figures.ChopEllipseConnector REF 20  
                CH.ifa.draw.standard.ChopBoxConnector REF 24    REF 3 REF 4 REF 15 REF 14 REF 24 REF 20 REF 9 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 4998 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 "Visibility" "Boolean" "TRUE" "FrameColor" "Color" 255 199 158 255 -11 -147 ":out(p2)" "SansSerif" 0 12 0 REF 14 
            CH.ifa.draw.standard.OffsetLocator 6 -22 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 5 
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 5007 "TextColor" "Color" 0 0 255 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 "FrameColor" "Color" 255 199 158 255 -16 -220 "[toAgent]" "SansSerif" 0 18 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator -35 -124 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 5004 "TextColor" "Color" 255 0 0 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 "FrameColor" "Color" 255 199 158 255 148 -7 ">" "SansSerif" 1 12 0 REF 15 
            CH.ifa.draw.standard.OffsetLocator 9 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 4994 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 "Visibility" "Boolean" "TRUE" "FrameColor" "Color" 255 199 158 255 -4 -33 "p2" "SansSerif" 0 12 0 REF 5 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 10 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 4995 "TextColor" "Color" 255 0 0 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 "FrameColor" "Color" 255 199 158 255 -10 -7 ">" "SansSerif" 1 12 0 REF 3 
            CH.ifa.draw.standard.OffsetLocator -11 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 5008 "TextColor" "Color" 0 0 255 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 "FrameColor" "Color" 255 199 158 255 -25 71 "[comment]" "SansSerif" 0 18 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator -37 167 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    REF 16 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 4993 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 "Visibility" "Boolean" "TRUE" "FrameColor" "Color" 255 199 158 255 -1 -99 "p2" "SansSerif" 0 12 0 REF 10 
            CH.ifa.draw.standard.OffsetLocator 3 -5 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 21 REF 26 REF 30 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 5006 "TextAlignment" "Int" 0 "FillColor" "Color" 255 199 158 255 -12 31 "$generateMessage" "SansSerif" 0 12 0 REF 3 
            CH.ifa.draw.standard.OffsetLocator 38 37 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 34 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 4996 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 25 -34 "OUT" "SansSerif" 1 12 0 REF 15 
            CH.ifa.draw.standard.OffsetLocator -104 -28 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  NULL  