12 
    de.renew.gui.CPNDrawing 12 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3486 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 47 -5 "PSPLIT" "SansSerif" 1 12 0 
            de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 3482 58 -208 20 20 NULL  
            CH.ifa.draw.standard.OffsetLocator 0 201 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.figures.RectangleFigure "attributes" "attributes" 3 "FigureWithID" "Int" 3475 "FrameColor" "Color" 224 224 224 255 "FillColor" "Color" 240 240 240 255 46 -222 44 436  
        de.renew.netcomponents.NetComponentFigure "attributes" "attributes" 3 "FigureWithID" "Int" 3485 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 6 REF 5 
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3479 2 68 11 68 193 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector 
                    de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 3476 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 192 192 192 255 56 -5 24 16 NULL   
                CH.ifa.draw.figures.ChopEllipseConnector 
                    de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 3480 58 192 20 20 NULL    
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3481 2 68 -5 68 -188 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 10  
                CH.ifa.draw.figures.ChopEllipseConnector REF 2   REF 12 REF 10 REF 2  REF 12 REF 10 REF 2 REF 7 REF 13 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 3484 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 255 0 0 255 "FillColor" "Color" 255 199 158 255 74 193 ">" "SansSerif" 1 12 0 REF 12 
            CH.ifa.draw.standard.OffsetLocator 9 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 3483 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 255 0 0 255 "FillColor" "Color" 255 199 158 255 75 -207 ">" "SansSerif" 1 12 0 REF 2 
            CH.ifa.draw.standard.OffsetLocator 10 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 3478 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 255 0 0 255 "FillColor" "Color" 255 199 158 255 53 -6 ">" "SansSerif" 1 12 0 REF 10 
            CH.ifa.draw.standard.OffsetLocator -12 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 3477 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 76 -32 "PSPLIT" "SansSerif" 1 12 0 REF 12 
            CH.ifa.draw.standard.OffsetLocator 29 -226 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  NULL  